s3-buffer:
  payload-storage-path: s3://bucket/nexus/payloads
  request-payload-proxy-configuration:
    tenant-id: "test-tenant"
    serve-path-template: "/data/v1/payloads/%s/%s"
    sign-secret: "test-secret"
  buffer-config:
    failure-rate-base-delay: 100ms
    failure-rate-max-delay: 1s
    rate-limit-elements-per-second: 10
    rate-limit-elements-burst: 100
    workers: 10
  access-key-id: "test"
  secret-access-key: "test"
  region: us-east-1
  endpoint: http://127.0.0.1:9000
runtime-namespace: nexus
deploy-namespace: nexus-scheduler
astra-cql-store: # can be read from environment
  secure-connection-bundle-base64: base64value
  gateway-user: user
  gateway-password: password
  indexes-supported: true
  keyspace: "nexus"
scylla-cql-store:
  hosts:
    - 127.0.0.1:9000
  indexes-supported: true
  keyspace: "nexus"
keyspaces-cql-store:
  hosts:
    - keyspaces.aws.com
  port: "9042"
  ca-path: "/tmp/ca"
  region: "us-east-1"
  keyspace: "nexus"
cql-store-type: cassandra-astra
kube-config-path: "/tmp/nexus-test"
shard-kube-config-path: "/tmp/shards"
max-payload-size: 500Mi
log-level: debug
