{{- if .Values.scheduler.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  appconfig.{{ .Values.environment | lower }}.yaml: |
    {{ .Values.scheduler.config.app }}
{{- end }}
