apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  appconfig.{{ .Values.environment | lower }}.yaml: |
    buffer:
      buffer-config:
        payload-storage-path: ""
        payload-valid-for: {{ .Values.buffer.payloadValidForDefault }}
        failure-rate-base-delay: {{ .Values.buffer.backOffBaseDelay }}
        failure-rate-max-delay: {{ .Values.buffer.backOffMaxDelay }}
        rate-limit-elements-per-second: {{ .Values.buffer.rateLimitElementsPerSecond }}
        rate-limit-elements-burst: {{ .Values.buffer.rateLimitElementsBurst }}
        workers: {{ .Values.buffer.workers }}
      access-key-id: ""
      secret-access-key: ""
      region: ""
      endpoint: ""
    resource-namespace: {{ .Values.scheduler.namespace }}
    cql-store:
      secure-connection-bundle-base64: ""
      gateway-user: ""
      gateway-password: ""
    kube-config-path: ""
    shard-kube-config-path: {{ .Values.scheduler.shardsConfigPath }}
