name: Release a new version

on: workflow_dispatch

permissions: {}

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write # create GitHub release and tag

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Create Release
        uses: SneaksAndData/github-actions/semver_release@6c8187f0d8c167a9410a76bed2e98409449ed495 # v0.1.11
        with:
          major_v: 1
          minor_v: 2
